### ISSUE TITLE
KeyError: 'token_bound_cidrs' in hashivault_userpass_update

### ISSUE THREAD

**Issue by ilyaevseev** [TerryHowe/ansible-modules-hashivault#354] opened 2021-08-10 12:01 UTC
Seems like previous state of updated user does not contain token_bound_cidrs:
```
hashivault_userpass.py, line 80, in hashivault_userpass_update
KeyError: 'token_bound_cidrs'
```

**Comment by TerryHowe** [comment] 2021-08-11 13:43
Hmm, I feel like this is caused by a recent change.

**Comment by TerryHowe** [comment] 2021-11-26 11:43
No recent change around that, I assume I haven't seen it because of the version of vault and hvac I'm using vs what you are using. This looks like it could be fixed in the module though.

**Comment by TerryHowe** [comment] 2021-11-26 12:07
https://github.com/TerryHowe/ansible-modules-hashivault/commit/83b8572980b0cb2608ee0ac0d0745bc86eb4b53a

Available in the next release

**Closed by TerryHowe** 2021-11-26 12:07 UTC
