### ISSUE TITLE
Error in module import

### ISSUE THREAD

**Issue by mg03** [TerryHowe/ansible-modules-hashivault#4] opened 2016-11-15 18:46 UTC
```
ansible --version
ansible 2.1.1.0
```
  
Playbook

```
- hosts: qa
  vars:
    url: 'http://localhost'
  tasks:
    - hashivault_status:
      register: 'vault_status'
    - debug: msg="{{ vault_status }}"
```

Error message that i get:
`{"failed": true, "msg": "Could not find imported module support code for hashivault_status.  Looked for either * or hashivault"}`

**Comment by TerryHowe** [comment] 2016-11-15 20:04
what version of ansible-modules-hashivault do you have installed.  I just tested with 2.1.1.0 and it is working for me:
```
hashivault $ ansible --version
ansible 2.1.1.0
  config file = /Users/THowe/crap/hashivault/ansible.cfg
  configured module search path = Default w/o overrides
hashivault $ ansible-playbook -v functional/test_status.yml 
Using /Users/THowe/crap/hashivault/ansible.cfg as config file

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [hashivault_status] *******************************************************
ok: [localhost] => {"changed": false, "rc": 0, "status": {"n": 5, "progress": 0, "sealed": false, "t": 3}}

TASK [assert] ******************************************************************
ok: [localhost] => {"changed": false, "msg": "all assertions passed"}

TASK [assert] ******************************************************************
ok: [localhost] => {"changed": false, "msg": "all assertions passed"}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   

hashivault $ pip list | grep ansible
DEPRECATION: The default format will switch to columns in the future. You can use --format=legacy (or define a list_format in your pip.conf) to disable this warning.
ansible (2.1.1.0)
ansible-modules-dcos (1.2.3)
ansible-modules-hashivault (2.5.6)
You are using pip version 9.0.0, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
hashivault $
```

**Comment by mg03** [comment] 2016-11-16 02:52
```pip search ansible-modules-hashivault | grep vault
ansible-vault (1.0.4)                   - R/W an ansible-vault yaml file
ansible-modules-hashivault (2.7.0)      - Ansible Modules for Hashicorp Vault```

and installed is 

```pip list | grep vault
ansible-modules-hashivault (2.7.0)```

**Comment by mg03** [comment] 2016-11-16 02:53
Is there a specific setting to be set in ansible.cfg ?

**Comment by TerryHowe** [comment] 2016-11-16 14:08
No special setting in ansible.cfg, that ansible.cfg checked into the repo is what I use for functional testing

**Comment by TerryHowe** [comment] 2016-11-16 14:58
There was a change to the installation procedure that may be causing this.  Could you try 
```
pip uninstall ansible
pip install ansible
```

**Comment by TerryHowe** [comment] 2016-11-16 14:58
That might help if you upgraded from 2.5 or so to 2.7

**Comment by mg03** [comment] 2016-11-16 19:38
I did not upgrade from 2.5 to 2.7. When I installed with pip I installed latest and 2.7 is the latest.

I can try to install 2.5.6 and see if that works. I can also uninstall and re-install ansible.

**Comment by TerryHowe** [comment] 2016-11-16 20:20
Don't install 2.5.6.  I'll try again from a completely fresh venv.

**Comment by TerryHowe** [comment] 2016-11-16 20:20
You are running Python 2.7, right?

**Comment by TerryHowe** [comment] 2016-11-16 20:48
Thinking about this some more, you are targeting the qa hosts and that host doesn't have ansible-modules-hashivault installed.  I guess to make that work, you'd need to install that or run your status on localhost

**Comment by mg03** [comment] 2016-11-17 08:06
ansible-modules-hashivault have been installed on the remote host. Python 2.7, Ansible=2.1.1.0

**Comment by TerryHowe** [comment] 2016-11-17 11:17
Did that help at all?

**Comment by mg03** [comment] 2016-11-17 22:46
Unfortunately, it did not. Same error.
{"failed": true, "msg": "Could not find imported module support code for hashivault_status. Looked for either * or hashivault"}

**Comment by TerryHowe** [comment] 2016-11-18 14:54
Well, I'm having a tough time because I can't reproduce this.  What happens when you do this:

```
ls -last  ${VIRTUAL_ENV}/lib/python2.7/site-packages/ansible/modules/hashivault
```

**Comment by mg03** [comment] 2016-11-21 04:27
```/usr/local/lib/python2.7/dist-packages/ansible/modules/hashivault# ls -last
total 164
4 drwxr-sr-x 2 root staff 4096 Nov 21 04:21 .
4 -rw-r--r-- 1 root staff 2161 Nov 21 04:21 hashivault_policy_list.pyc
4 -rw-r--r-- 1 root staff 2336 Nov 21 04:21 hashivault_userpass_delete.pyc
4 -rw-r--r-- 1 root staff  164 Nov 21 04:21 __init__.pyc
4 -rw-r--r-- 1 root staff 2097 Nov 21 04:21 hashivault_audit_list.pyc
4 -rw-r--r-- 1 root staff 2521 Nov 21 04:21 hashivault_auth_enable.pyc
4 -rw-r--r-- 1 root staff 2137 Nov 21 04:21 hashivault_auth_list.pyc
4 -rw-r--r-- 1 root staff 2415 Nov 21 04:21 hashivault_policy_delete.pyc
4 -rw-r--r-- 1 root staff 2369 Nov 21 04:21 hashivault_policy_get.pyc
4 -rw-r--r-- 1 root staff 2355 Nov 21 04:21 hashivault_policy_set.pyc
4 -rw-r--r-- 1 root staff 3049 Nov 21 04:21 hashivault_read.pyc
4 -rw-r--r-- 1 root staff 2671 Nov 21 04:21 hashivault_secret_disable.pyc
4 -rw-r--r-- 1 root staff 2912 Nov 21 04:21 hashivault_secret_enable.pyc
4 -rw-r--r-- 1 root staff 2147 Nov 21 04:21 hashivault_secret_list.pyc
4 -rw-r--r-- 1 root staff 2287 Nov 21 04:21 hashivault_unseal.pyc
4 -rw-r--r-- 1 root staff 2736 Nov 21 04:21 hashivault_userpass_create.pyc
4 -rw-r--r-- 1 root staff 3018 Nov 21 04:21 hashivault_write.pyc
4 drwxr-sr-x 5 root staff 4096 Nov 21 04:21 ..
4 -rw-r--r-- 1 root staff 2674 Nov 21 04:21 hashivault_audit_enable.pyc
4 -rw-r--r-- 1 root staff 2111 Nov 21 04:21 hashivault_init.pyc
4 -rw-r--r-- 1 root staff 2136 Nov 21 04:21 hashivault_seal.pyc
4 -rw-r--r-- 1 root staff 2114 Nov 21 04:21 hashivault_status.pyc
4 -rw-r--r-- 1 root staff 2083 Oct 23 18:51 hashivault_secret_disable.py
4 -rw-r--r-- 1 root staff 2428 Oct 23 18:40 hashivault_secret_enable.py
4 -rw-r--r-- 1 root staff 1587 Oct 23 18:03 hashivault_secret_list.py
4 -rw-r--r-- 1 root staff 2170 Oct 14 13:17 hashivault_audit_enable.py
4 -rw-r--r-- 1 root staff 1539 Oct 14 13:17 hashivault_audit_list.py
4 -rw-r--r-- 1 root staff 1984 Oct 14 13:17 hashivault_auth_enable.py
4 -rw-r--r-- 1 root staff 1581 Oct 14 13:17 hashivault_auth_list.py
4 -rw-r--r-- 1 root staff 1589 Oct 14 13:17 hashivault_init.py
4 -rw-r--r-- 1 root staff 1829 Oct 14 13:17 hashivault_policy_delete.py
4 -rw-r--r-- 1 root staff 1791 Oct 14 13:17 hashivault_policy_get.py
4 -rw-r--r-- 1 root staff 1612 Oct 14 13:17 hashivault_policy_list.py
4 -rw-r--r-- 1 root staff 1802 Oct 14 13:17 hashivault_policy_set.py
4 -rw-r--r-- 1 root staff 2657 Oct 14 13:17 hashivault_read.py
4 -rw-r--r-- 1 root staff 1583 Oct 14 13:17 hashivault_seal.py
4 -rw-r--r-- 1 root staff 1576 Oct 14 13:17 hashivault_status.py
4 -rw-r--r-- 1 root staff 1702 Oct 14 13:17 hashivault_unseal.py
4 -rw-r--r-- 1 root staff 2198 Oct 14 13:17 hashivault_userpass_create.py
4 -rw-r--r-- 1 root staff 1746 Oct 14 13:17 hashivault_userpass_delete.py
4 -rw-r--r-- 1 root staff 2695 Oct 14 13:17 hashivault_write.py
0 -rw-r--r-- 1 root staff    0 Oct 14 13:17 __init__.py```

**Comment by TerryHowe** [comment] 2017-01-03 21:30
Cannot reproduce, reopen if still having issues.  Maybe a fresh install of ansible would of helped here.

**Closed by TerryHowe** 2017-01-03 21:31 UTC

**Comment by DrumSergio** [comment] 2019-01-19 20:49
The same happened to me, in a fresh install of Ansible 2.7.6 with Python 2.7.12
