### ISSUE TITLE
Broken Compatibility for write for pki

### ISSUE THREAD

**Issue by seeder** [TerryHowe/ansible-modules-hashivault#6] opened 2016-11-28 15:37 UTC
We were using your module to issue pki certs from vault, now we do not get the data back sent by vault only a message written by your module... it would be useful to actually have it working again

**Comment by TerryHowe** [comment] 2016-11-28 15:40
I could use a pip list, environment you are working in, what command you are running and the output

**Comment by seeder** [comment] 2016-11-28 17:01
We have used this construct : 
```- name: Request Cert
  hashivault_write:
    token: "{{vault_pki_token}}"
    url: "{{vault_pki_url}}"
    secret: "/{{vault_pki_path}}/issue/{{vault_pki_role}}"
    data: "{{vault_pki_issue_}}"
  register: vault_pki_issue_result
  run_once: yes
```

and inside `vault_pki_issue_result` was data with certificate and key now there is only msg. :(

**Comment by TerryHowe** [comment] 2016-11-28 18:19
And the message is?

**Comment by TerryHowe** [comment] 2016-11-28 18:20
I also need the version of ansible-module-hashivault you are running

**Comment by TerryHowe** [comment] 2016-11-28 19:16
it may be that leading '/' on your secret name.  Is that secret on the mount point /secret or /{{vault_pki_path}}?

**Comment by seeder** [comment] 2016-11-29 10:02
What gets returned is ```{
        "changed": true, 
        "msg": "Secret /devops-pki/issue/config-uksouth-staging written", 
        "rc": 0
    }```

`vault_pki_path` is a path to mounted PKI backed https://www.vaultproject.io/docs/secrets/pki/index.html

**Comment by seeder** [comment] 2016-11-29 10:34
Tried with latest version from this repo also using hvac 0.2.16

**Comment by seeder** [comment] 2016-11-29 11:07
btw we actually have forked your repo and made improvements to previous version. 

So it looks like this functionality was never in your version https://github.com/generiklimited/ansible-modules-hashivault , sorry!

**Comment by TerryHowe** [comment] 2016-11-30 15:34
I'm not following on what the problem is with ```{ "changed": true, "msg": "Secret /devops-pki/issue/config-uksouth-staging written", "rc": 0 }``` is that the incorrect mount point?

There was a change around 2.9 where if the secret name starts with / it is assumed absolute path meaning you are specifying the mount point.  It doesn't assume that the mount point ins /secret anymore.  I assume this is what you are seeing.

**Comment by TerryHowe** [comment] 2016-11-30 15:35
If you have any more PRs, that'd probably make life easier for both of us.

**Comment by seeder** [comment] 2016-12-01 13:36
Mount point is correct, however, client.write returns data from vault response, and it is required for use with PKI. ( as when you write to pki/issue/role  it returns the certificate and key ) 

I will write the patch it requires for your latest version when I get a spare time.

**Comment by TerryHowe** [comment] 2016-12-02 14:28
https://pypi.python.org/pypi/ansible-modules-hashivault/2.10.0 new release should have what you want

**Comment by TerryHowe** [comment] 2016-12-02 14:32
I'm going to close this out, if you have something else, reopen or make a new issue, thanks for the PR!

**Closed** 2017-01-03 21:30 UTC
