### ISSUE TITLE
hashivault_oidc_auth_method_config won't update existing oidc auth config

### ISSUE THREAD

**Issue by masterphenix** [TerryHowe/ansible-modules-hashivault#214] opened 2020-04-08 16:00 UTC
Hello,

I am using hashivault_oidc_auth_method_config to create / update the oidc auth method config ; each time the task is ran, the oidc_client_secret changes :
```ansible
- name: "Configure OIDC auth method"
  hashivault_oidc_auth_method_config:
    url: "{{ vault_addr }}"
    token: "{{ root_token }}"
    oidc_discovery_url: "https://login.microsoftonline.com/tenant_id/v2.0"
    oidc_client_id: "xxxx-yyy-zzzz"
    oidc_client_secret: "mypassword"
    default_role: "admin"
```
First time run, this works fine : config is created, and authentication with my azure provider works.
Second time, though, I get the following error (with -vvvv) :
```
TASK [vault-configure : Configure OIDC auth method] ************************************************************************************************************************************
task path: /home/sr/git/production/ansible-vault/roles/vault-configure/tasks/main.yml:47
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: sr
<localhost> EXEC /bin/sh -c 'echo ~sr && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/sr/.ansible/tmp/ansible-tmp-1586361411.34-149731349480909 `" && echo ansible-tmp-1586361411.34-149731349480909="` echo /home/sr/.ansible/tmp/ansible-tmp-1586361411.34-149731349480909 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/dist-packages/ansible-2.10.0.dev0-py2.7.egg/ansible/modules/hashivault/hashivault_oidc_auth_method_config.py
<localhost> PUT /home/sr/.ansible/tmp/ansible-local-1742QUilwS/tmpV4q9M2 TO /home/sr/.ansible/tmp/ansible-tmp-1586361411.34-149731349480909/AnsiballZ_hashivault_oidc_auth_method_config.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/sr/.ansible/tmp/ansible-tmp-1586361411.34-149731349480909/ /home/sr/.ansible/tmp/ansible-tmp-1586361411.34-149731349480909/AnsiballZ_hashivault_oidc_auth_method_config.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/sr/.ansible/tmp/ansible-tmp-1586361411.34-149731349480909/AnsiballZ_hashivault_oidc_auth_method_config.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/sr/.ansible/tmp/ansible-tmp-1586361411.34-149731349480909/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "authtype": "token",
            "bound_issuer": "",
            "ca_cert": "",
            "ca_path": "",
            "client_cert": "",
            "client_key": "",
            "default_role": "admin",
            "jwks_ca_pem": "",
            "jwks_url": null,
            "jwt_supported_algs": [],
            "jwt_validation_pubkeys": [],
            "mount_point": "oidc",
            "namespace": null,
            "oidc_client_id": "xxxx-yyy-zzzz",
            "oidc_client_secret": "mypassword2",
            "oidc_discovery_ca_pem": "",
            "oidc_discovery_url": "https://login.microsoftonline.com/tenant_id/v2.0",
            "password": "",
            "role_id": "",
            "secret_id": "",
            "token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url": "https://myvaultaddress.com",
            "username": "",
            "verify": true
        }
    },
    "msg": "Exception: u'oidc_response_mode'",
    "rc": 1
}
```

Using ansible 2.10.0.dev0 with ansible-modules-hashivault installed from pip (today).

**Comment by TerryHowe** [comment] 2020-04-09 21:33
Very likely, this is being generated here: https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_oidc_auth_method_config.py#L196

**Comment by TerryHowe** [comment] 2020-04-09 21:47
I pushed a change to master to hopefully fix this issue, so that line probably shows the change now

**Comment by TerryHowe** [comment] 2020-04-10 00:03
Should be fixed on 4.3.1

**Comment by masterphenix** [comment] 2020-04-12 16:49
I confirm the error is gone (I just updated to 4.3.2), but still the configuration is not updated. If the configuration exists, it is not updated, even if a parameter differs (the oidc_client_secret in my case).
I get "OK" instead of "changed" :
```
TASK [vault-configure : Configure OIDC auth method] ************************************************************************************************************************************
ok: [localhost]
```
And if I try OIDC login in Vault after running the playbook, it fails :
```
Vault login failed. Error exchanging oidc code: "oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\":\"invalid_client\",\"error_description\":\"AADSTS7000215: Invalid client secret is provided
```

**Comment by TerryHowe** [comment] 2020-04-12 20:03
can you run that verbose?

**Comment by masterphenix** [comment] 2020-04-13 05:54
Sure, here is the task result with -vvvv :
```
TASK [vault-configure : Configure OIDC auth method] ************************************************************************************************************************************
task path: /home/sr/git/production/ansible-vault/roles/vault-configure/tasks/main.yml:48
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: sr
<localhost> EXEC /bin/sh -c 'echo ~sr && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/sr/.ansible/tmp/ansible-tmp-1586757092.6-152904978509967 `" && echo ansible-tmp-1586757092.6-152904978509967="` echo /home/sr/.ansible/tmp/ansible-tmp-1586757092.6-152904978509967 `" ) && sleep 0'
Using module file /home/sr/.local/lib/python2.7/site-packages/ansible/modules/hashivault/hashivault_oidc_auth_method_config.py
<localhost> PUT /home/sr/.ansible/tmp/ansible-local-10380HDCAWI/tmpyDZ7lv TO /home/sr/.ansible/tmp/ansible-tmp-1586757092.6-152904978509967/AnsiballZ_hashivault_oidc_auth_method_config.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/sr/.ansible/tmp/ansible-tmp-1586757092.6-152904978509967/ /home/sr/.ansible/tmp/ansible-tmp-1586757092.6-152904978509967/AnsiballZ_hashivault_oidc_auth_method_config.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/sr/.ansible/tmp/ansible-tmp-1586757092.6-152904978509967/AnsiballZ_hashivault_oidc_auth_method_config.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/sr/.ansible/tmp/ansible-tmp-1586757092.6-152904978509967/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "authtype": "token",
            "bound_issuer": "",
            "ca_cert": "",
            "ca_path": "",
            "client_cert": "",
            "client_key": "",
            "default_role": "admin",
            "jwks_ca_pem": "",
            "jwks_url": null,
            "jwt_supported_algs": [],
            "jwt_validation_pubkeys": [],
            "mount_point": "oidc",
            "namespace": null,
            "oidc_client_id": "myclientid",
            "oidc_client_secret": "myclientsecret",
            "oidc_discovery_ca_pem": "",
            "oidc_discovery_url": "https://login.microsoftonline.com/tenantid/v2.0",
            "password": "",
            "role_id": "",
            "secret_id": "",
            "token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url": "https://vault.domain",
            "username": "",
            "verify": true
        }
    },
    "rc": 0
}
```

**Comment by TerryHowe** [comment] 2020-04-14 19:47
I don't have an oidc service to test with, so a bit hard for me to reproduce, but I noticed this:

https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_oidc_auth_method_config.py#L203

The person that developed this module specifically sets oidc_client_secret *after* checking if there is changed. I feel like this was a case where the values isn't returned or is obfuscated, so we really cannot support update.

As a work around, you might be able to make some trival update to some other value to trigger the update, but I don't see one that would be useful for that (something like description).

**Comment by TerryHowe** [comment] 2020-04-16 16:14
I'm going to close this out because it seems it cannot be resolved. Open another issue if you have some other ideas, thanks.

**Closed by TerryHowe** 2020-04-16 16:14 UTC
